[core]
max_cpus = "2"

[log]
output = "stdout"
mode = "dev"
level = "debug"

[http]
enabled_services = ["appregistrysvc", "datasvc", "ocdavsvc", "ocssvc", "oidcprovider", "wellknown","preferencessvc", "iframeuisvc"]
#enabled_middlewares = ["log", "trace", "auth", "cors"]
enabled_middlewares = ["log", "trace", "auth", "cors"]
network = "tcp"
address = "0.0.0.0:9998"

[http.middlewares.trace]
priority = 100
header = "x-trace"

[http.middlewares.log]
priority = 200

[http.middlewares.auth]
priority = 300
authsvc = "127.0.0.1:9999"
credential_strategy = "oidc"
#credential_strategy = "basic"
token_strategy = "header"
token_writer = "header"
token_manager = "jwt"
skip_methods = [
    "/status.php",
    "/oauth2",
    "/oauth2/auth", 
    "/oauth2/token", 
    "/oauth2/introspect",
    "/oauth2/userinfo", 
    "/oauth2/sessions", 
    "/.well-known/openid-configuration",
    "/data"
]

[http.middlewares.cors]
priority = 400
allowed_origins = ["*"]
allow_credentials = true
allowed_methods = ["OPTIONS", "GET", "PUT", "POST", "DELETE", "MKCOL", "PROPFIND", "PROPPATCH", "MOVE", "COPY", "REPORT", "SEARCH"]
allowed_headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "Authorization", "Ocs-Apirequest"]
options_passthrough = true

[http.middlewares.auth.token_managers.jwt]
secret = "Pive-Fumkiu4"

[http.middlewares.auth.token_strategies.header]
header = "X-Access-Token"

[http.middlewares.auth.token_writers.header]
header = "X-Access-Token"

[http.services.appregistrysvc]
prefix = "appregistry"
gatewaysvc = "localhost:9999"

[http.services.preferencessvc]
prefix = "preferences"
preferencessvc = "localhost:9999"

[http.services.iframeuisvc]
prefix = "iframe"

[http.services.ocdavsvc]
prefix = ""
chunk_folder = "/var/tmp/owncloud/chunks"
storageregistrysvc = "127.0.0.1:9999"
storageprovidersvc = "127.0.0.1:9999"
enable_cors = true

[http.services.ocssvc]
prefix = "ocs"
publicshareprovidersvc = "" # "" = disabled
usershareprovidersvc = "127.0.0.1:9999"
storageprovidersvc = "127.0.0.1:9999"
user_manager = "oidc"

[http.services.ocssvc.user_managers.json]
users = "users.json"

[http.services.ocssvc.config]
version = "1.8"
website = "nexus"
host = "https://localhost:9998"
contact = "admin@localhost"
ssl = "true"
[http.services.ocssvc.capabilities.capabilities.core]
poll_interval = 60
webdav_root = "remote.php/webdav"
[http.services.ocssvc.capabilities.capabilities.core.status]
installed = true
maintenance = false
needsDbUpgrade = false
version = "10.0.9.5"
versionstring = "10.0.9"
edition = "community"
productname = "reva"
hostname = ""
[http.services.ocssvc.capabilities.capabilities.checksums]
supported_types = ["SHA256"]
preferred_upload_type = "SHA256"
[http.services.ocssvc.capabilities.capabilities.files]
private_links = true
bigfilechunking = true
blacklisted_files = ["foo"]
undelete = true
versioning = true
[http.services.ocssvc.capabilities.capabilities.dav]
chunking = "1.0"
[http.services.ocssvc.capabilities.capabilities.files_sharing]
api_enabled = true
resharing = true
group_sharing = true
auto_accept_share = true
share_with_group_members_only = true
share_with_membership_groups_only = true
default_permissions = 22
search_min_length = 3
[http.services.ocssvc.capabilities.capabilities.files_sharing.public]
enabled = true
send_mail = true
social_share = true
upload = true
multiple = true
supports_upload_only = true
[http.services.ocssvc.capabilities.capabilities.files_sharing.public.password]
enforced = true
[http.services.ocssvc.capabilities.capabilities.files_sharing.public.password.enforced_for]
read_only = true
read_write = true
upload_only = true
[http.services.ocssvc.capabilities.capabilities.files_sharing.public.expire_date]
enabled = true
[http.services.ocssvc.capabilities.capabilities.files_sharing.user]
send_mail = true
[http.services.ocssvc.capabilities.capabilities.files_sharing.user_enumeration]
enabled = true
group_members_only = true
[http.services.ocssvc.capabilities.capabilities.files_sharing.federation]
outgoing = true
incoming = true
[http.services.ocssvc.capabilities.capabilities.notifications]
endpoints = ["list", "get", "delete"]
[http.services.ocssvc.capabilities.version]
edition = "nexus"
major = 10
minor = 0
micro = 11
string = "10.0.11"

[http.services.datasvc]
driver = "local"
prefix = "data"
temp_folder = "/var/tmp/"

[http.services.datasvc.drivers.local]
root = "/data"

[http.services.datasvc.drivers.owncloud]
datadirectory = "/data"

[http.services.wellknown]
prefix = ".well-known"

[http.services.oidcprovider]
prefix = "oauth2"

## authsvc part

[grpc]
network = "tcp"
address = "0.0.0.0:9999"
access_log = "stderr"
#tls_enabled = true
#tls_cert = "/etc/gridsecurity/host.cert"
#tls_key = "/etc/gridsecurity/host.key"
enabled_services = ["authsvc", "usershareprovidersvc", "storageregistrysvc", "storageprovidersvc","preferencessvc","appregistrysvc"]
enabled_interceptors = ["auth", "prometheus", "log", "trace"]


[grpc.interceptors.trace]
priority = 100
header = "x-trace"

[grpc.interceptors.log]
priority = 200

[grpc.interceptors.prometheus]
priority = 300

[grpc.interceptors.auth]
priority = 400
# TODO grpc 'headers' are stored as google.golang.org/grpc/metadata ... needs better naming, this is too confusing
# keys for grpc metadata are always lowercase, so interceptors headers need to use lowercase.
header = "x-access-token"
token_strategy = "header"
token_manager = "jwt"
# GenerateAccessToken contains the credentials in the payload. Skip auth, otherwise services cannot obtain a token.
skip_methods = ["/cs3.authv0alpha.AuthService/GenerateAccessToken"]

[grpc.interceptors.auth.token_strategies.header]
header = "X-Access-Token"

[grpc.interceptors.auth.token_managers.jwt]
secret = "Pive-Fumkiu4"


[grpc.services.authsvc]
auth_manager = "oidc"
user_manager = "oidc"
token_manager = "jwt"

[grpc.services.authsvc.token_managers.jwt]
secret = "Pive-Fumkiu4"

[grpc.services.authsvc.auth_managers.oidc]
provider = "http://localhost:9998"
insecure = true
# the client credentials for the token introspection beckchannel
client_id = "reva"
client_secret = "foobar"

[grpc.services.authsvc.auth_managers.json]
users = "users.json"

[grpc.services.authsvc.user_managers.json]
users = "users.json"

[grpc.services.storageregistrysvc]
driver = "static"

[grpc.services.storageregistrysvc.drivers.static.rules]
"/" = "127.0.0.1:9999"
"123e4567-e89b-12d3-a456-426655440000" = "127.0.0.1:9999"


[grpc.services.storageprovidersvc]
driver = "local"
mount_path = "/"
mount_id = "123e4567-e89b-12d3-a456-426655440000"
data_server_url = "http://127.0.0.1:9998/data"

[grpc.services.storageprovidersvc.available_checksums]
md5   = 100
unset = 1000

[grpc.services.storageprovidersvc.drivers.local]
root = "/data"

[grpc.services.storageprovidersvc.drivers.owncloud]
datadirectory = "/data"

[grpc.services.usershareprovidersvc]
driver = "local"

[grpc.services.usershareprovidersvc.drivers.local]
root = "/data"

[grpc.services.usershareprovidersvc.drivers.owncloud]
datadirectory = "/data"

[grpc.services.appregistrysvc]
driver = "static"

[grpc.services.appregistrysvc.static.rules]
"application/x-root" = "root.cern/js/latest"

[grpc.services.appprovidersvc]
driver = "demo"

[grpc.services.appprovidersvc.demo]
iframe_ui_provider = "http://localhost:9998/iframe"
